openapi: 3.0.0
info:
  title: Drilunia API
  version: 1.0.0
  description: API profesional para Drilunia (chat, auth, notificaciones, archivos, WebRTC)
servers:
  - url: http://localhost:4000
paths:
  /api/auth/register:
    post:
      summary: Registro de usuario
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                email:
                  type: string
                password:
                  type: string
                name:
                  type: string
      responses:
        '201':
          description: Usuario registrado
  /api/auth/login:
    post:
      summary: Login de usuario
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                email:
                  type: string
                password:
                  type: string
      responses:
        '200':
          description: Login exitoso
  /api/chat/send:
    post:
      summary: Enviar mensaje de chat
      security:
        - bearerAuth: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                toUserId:
                  type: integer
                content:
                  type: string
      responses:
        '201':
          description: Mensaje enviado
  /api/ice:
    get:
      summary: Obtener configuración ICE (TURN/STUN)
      security:
        - bearerAuth: []
      responses:
        '200':
          description: Configuración ICE
components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT 